function obtenerItemSpanish(argument0) //gml_Script_obtenerItemSpanish
{
    buscar = argument0
    objetos = ds_map_create()
    ds_map_add(objetos, "Croquet Roll", "Rollo Croq.")
    ds_map_add(objetos, "Stick", "Palo")
    ds_map_add(objetos, "Bandage", "Vendaje")
    ds_map_add(objetos, "Rock Candy", "Roca Car.")
    ds_map_add(objetos, "Pumpkin Rings", "Anillo Calab.")
    ds_map_add(objetos, "Stoic Onion", "Cebolla Est.")
    ds_map_add(objetos, "Ghost Fruit", "Fruta Fant.")
    ds_map_add(objetos, "Spider Cider", "Cidra Araña")
    ds_map_add(objetos, "Butterscotch Pie", "Tarta Caram.")
    ds_map_add(objetos, "Faded Ribbon", "Cinta Dest.")
    ds_map_add(objetos, "Tough Glove", "Guante Duro")
    ds_map_add(objetos, "Manly Bandanna", "Bandana Var.")
    ds_map_add(objetos, "Snowman Piece", "Trozo de Ni.")
    ds_map_add(objetos, "Nice Cream", "Helagradable")
    ds_map_add(objetos, "Puppydough Icecream", "Helado Cach.")
    ds_map_add(objetos, "Bisicle", "Bizcocho")
    ds_map_add(objetos, "Unisicle", "Uniscocho")
    ds_map_add(objetos, "Cinnamon Bun", "Conejo Can.")
    ds_map_add(objetos, "Temmie Flakes", "Copo Temmie")
    ds_map_add(objetos, "Abandoned Quiche", "Quiche Aban.")
    ds_map_add(objetos, "Old Tutu", "Viejo Tutú")
    ds_map_add(objetos, "Ballet Shoes", "Zapatos Bal.")
    ds_map_add(objetos, "Punch Card", "Tarjeta Perf.")
    ds_map_add(objetos, "Annoying Dog", "Perro Molesto")
    ds_map_add(objetos, "Dog Salad", "Ens. para Per.")
    ds_map_add(objetos, "Dog Residue", "Resudio Perro")
    ds_map_add(objetos, "Astronaut Food", "Comida Astr.")
    ds_map_add(objetos, "Instant Noodles", "Fideos Inst.")
    ds_map_add(objetos, "Crab Apple", "Manzana Cangr.")
    ds_map_add(objetos, "Hot Cat", "Gatito Cal.")
    ds_map_add(objetos, "Glamburger", "Glamburguesa")
    ds_map_add(objetos, "Starfait", "Cebo Estelar")
    ds_map_add(objetos, "Legendary Hero", "Héroe Legen.")
    ds_map_add(objetos, "Butty Glasses", "Gafas Prot.")
    ds_map_add(objetos, "Torn Notebook", "Cuad. Rasgado")
    ds_map_add(objetos, "Stained Apron", "Delan. Manch.")
    ds_map_add(objetos, "Burnt Pan", "Sartén Quem.")
    ds_map_add(objetos, "Cowboy Hat", "Somb. de Vaq.")
    ds_map_add(objetos, "Empty Gun", "Pist. Vacía")
    ds_map_add(objetos, "Heart Locket", "Medallón Cor.")
    ds_map_add(objetos, "Worn Dagger", "Daga Desg.")
    ds_map_add(objetos, "Real Knife", "Cuch. Real")
    ds_map_add(objetos, "The Locket", "El Medallón")
    ds_map_add(objetos, "Bad Memory", "Malos Rec.")
    ds_map_add(objetos, "Dream", "Sueño")
    ds_map_add(objetos, "Undyne's Letter", "Carta Undyne")
    ds_map_add(objetos, "Undyne Letter EX", "Car. Und. EX")
    ds_map_add(objetos, "Junk Food 0", "Comida Ch. 0")
    ds_map_add(objetos, "Mystery Key", "Llave Mist.")
    ds_map_add(objetos, "Face Steak", "Cara Filete")
    ds_map_add(objetos, "Hush Puppy", "Cach. Silenc.")
    ds_map_add(objetos, "Snail Pie", "Tarta de Car.")
    ds_map_add(objetos, "temy armor", "Armadura Temy")
    ds_map_add(objetos, "Wild Revolver", "Revólver Sal.")
    ds_map_add(objetos, "Glass Ammo", "Balas de Vid.")
    ds_map_add(objetos, "Golden Cactus", "Cactus Dorado")
    ds_map_add(objetos, "Soggy Mitten", "Guante Mojado")
    ds_map_add(objetos, "Lemonade", "Limonada")
    ds_map_add(objetos, "Candy Corn", "Caram. Maíz")
    ds_map_add(objetos, "G. Pear", "Pera D.")
    ds_map_add(objetos, "Corn Dog", "Perro de Maíz")
    ds_map_add(objetos, "Patch", "Parche")
    ds_map_add(objetos, "Feather", "Pluma")
    ds_map_add(objetos, "G. Bandana", "Pañuelo Dor.")
    ds_map_add(objetos, "Pebble Ammo", "Piedras")
    ds_map_add(objetos, "Silver Ammo", "Balas de Plata")
    ds_map_add(objetos, "Glass Ammo", "Balas de Vid.")
    ds_map_add(objetos, "Missing Poster", "Poster Desaparecidos")
    ds_map_add(objetos, "Rubber Ammo", "Balas de Goma")
    ds_map_add(objetos, "Sponge Cake", "Pastel Espon.")
    ds_map_add(objetos, "Hndw Coffee", "Café Hndw")
    ds_map_add(objetos, "Hndw Pancake", "Panqueque")
    ds_map_add(objetos, "G.B. Bear", "G.B. Oso")
    ds_map_add(objetos, "Hot Pop", "Pal. Caliente")
    ds_map_add(objetos, "Lukewarm Pop", "Pal. Tibia")
    ds_map_add(objetos, "Cold Pop", "Pal. Fría")
    ds_map_add(objetos, "G. Coffee", "Café D.")
    ds_map_add(objetos, "G. Cactus", "Cactus Dorado")
    ds_map_add(objetos, "Adult Soda", "Soda +18")
    ds_map_add(objetos, "Packing Peanuts", "Paq. de Nueces")
    ds_map_add(objetos, "Trail Mix", "Frutos Secos")
    ds_map_add(objetos, "Ice Tea", "Té Helado")
    ds_map_add(objetos, "Green Tea", "Té Verde")
    ds_map_add(objetos, "Sea Tea", "Té de Mar")
    ds_map_add(objetos, "Fruitcake", "Past. Frutas")
    ds_map_add(objetos, "Spider Donut", "Dona Araña")
    ds_map_add(objetos, "Icewater", "Aguhelada")
    ds_map_add(objetos, "Oasis Latte", "Latte Oasis")
    ds_map_add(objetos, "Cnm. Cookie", "Galleta Can.")
    ds_map_add(objetos, "Root Beer", "Cerveza Raíz")
    ds_map_add(objetos, "Gunpowder", "Pólvora")
    ds_map_add(objetos, "Moss Salad", "Ensal. Musgo")
    ds_map_add(objetos, "Grassy Fries", "Pata. Frit.")
    ds_map_add(objetos, "Flower Stew", "G. de Flores")
    ds_map_add(objetos, "Gravity Granola", "G. Gravedad")
    ds_map_add(objetos, "Popato Chisps", "Papit. Frit.")
    ds_map_add(objetos, "Beef Jerky", "Carne Seca")
    ds_map_add(objetos, "Cake", "Pastel")
    ds_map_add(objetos, "Floral Cupcake", "Pastel Flor.")
    ds_map_add(objetos, "Hot Dog", "Perrito Cal.")
    ds_map_add(objetos, "Monster Candy", "CrmMnstr")
    ds_map_add(objetos, "Monster Candy+", "CrmMnstr+")
    ds_map_add(objetos, "C-B Strudel", "Pudín C-B")
    ds_map_add(objetos, "Corn Chowder", "Sopa de Maíz")
    ds_map_add(objetos, "Feisty Slider", "Hamb. Feisty")
    ds_map_add(objetos, "Honeydew Pin", "Br. Hndw")
    ds_map_add(objetos, "Band Merch Pin", "Br. de Banda")
    ds_map_add(objetos, "Steel Buckle", "Heb. Acero")
    ds_map_add(objetos, "Safety Jacket", "Chaq. Segura")
    ds_map_add(objetos, "Safety Goggles", "Gaf. Seguras")
    ds_map_add(objetos, "Delta Rune Patch", "Broche Delta")
    ds_map_add(objetos, "Silver Scarf", "Pañ. Plat.")
    ds_map_add(objetos, "Lukewarm Coffee", "Café Tibio")
    ds_map_add(objetos, "Soggy Mitten", "Guante Mojado")
    ds_map_add(objetos, "Matches", "Fósforos")
    ds_map_add(objetos, "Snowdin Map", "Mapa Snow.")
    ds_map_add(objetos, "Pickaxe", "Pico")
    ds_map_add(objetos, "Ice Pellets", "Balas Hel.")
    ds_map_add(objetos, "Cff Bean Ammo", "Balas Café")
    ds_map_add(objetos, "Super Ammo", "Super Balas")
    ds_map_add(objetos, "Flint", "Balas de Pi.")
    ds_map_add(objetos, "Nails", "Clavos")
    ds_map_add(objetos, "Friendliness Pellets", "Bolit. Amis.")
    ds_map_add(objetos, "Golden Scarf", "Pañuelo Dor.")
    ds_map_add(objetos, "Fancy Holster", "F. Elegante")
    ds_map_add(objetos, "Videotape", "Cinta Vídeo")
    ds_map_add(objetos, "H. Acid", "H. Ácido")
    ds_map_add(objetos, "Necklace", "Collar Roto")
    ds_map_add(objetos, "Dihydrogen Monoxide", "H2O")
    ds_map_add(objetos, "Toy Gun", "Arma de Juguete")
    ds_map_add(objetos, "Worn Hat", "Sombrero")
    ds_map_add(objetos, "Fancy Holster", "Funda de Lujo")
    ds_map_add(objetos, "Nice Hat", "Lindo Sombr.")
    if ds_map_exists(objetos, buscar)
        return ds_map_find_value(objetos, buscar);
    return buscar;
}

