if (control_test == 0)
{
    draw_set_color(c_white)
    draw_set_font(fnt_mainb)
    draw_set_halign(fa_center)
    draw_text((__view_get((0 << 0), 0) + 200), (__view_get((1 << 0), 0) + 13), string_hash_to_newline("MOBILE PORT"))
    draw_set_font(fnt_battle)
    draw_set_halign(fa_left)
    var xx = (__view_get((0 << 0), 0) + 20)
    if (p[0] == 1)
        draw_set_color(c_yellow)
    draw_text(xx, (__view_get((1 << 0), 0) + 44), string_hash_to_newline("Exit"))
    draw_set_color(c_white)
    if (p[1] == 1)
        draw_set_color(c_yellow)
    draw_text(xx, (__view_get((1 << 0), 0) + 79), string_hash_to_newline("MADE BY ATESQUIK"))
    draw_set_color(c_white)
    if (p[2] == 1)
        draw_set_color(c_yellow)
    draw_text(xx, ((__view_get((1 << 0), 0) + 94) + 30), string_hash_to_newline("UPDATE 1.1 CHANGELOG:"))
    draw_set_color(c_white)
    if (p[3] == 1)
        draw_set_color(c_yellow)
    draw_text(xx, ((__view_get((1 << 0), 0) + 109) + 30), string_hash_to_newline("ADDED MUSIC"))
    draw_set_color(c_white)
    if (p[4] == 1)
        draw_set_color(c_yellow)
    draw_text(xx, ((__view_get((1 << 0), 0) + 124) + 30), string_hash_to_newline("READJUSTED CONTROLS"))
    draw_set_color(c_white)
    if (p[6] == 1)
        draw_set_color(c_yellow)
    draw_text(xx, ((__view_get((1 << 0), 0) + 139) + 30), string_hash_to_newline("SOME BUGS FIXED"))
    draw_set_color(c_white)
}
