persistent = true
depth = -99999
control_fixture = physics_fixture_create()
physics_fixture_set_awake(control_fixture, 1)
settings_font = 1
settings_num_x = 477
zx = 250
zy = 170
xx = 290
xy = 140
cx = 330
cy = 110
button_scale = 1.6
analog_scale = 1.6
analog_posx = -37
analog_posy = 137.5
analog_edit_selected = 0
analog_center_x = (analog_posx + (((59 * analog_scale) / 2) - ((41 * analog_scale) / 2)))
analog_center_y = (analog_posy + (((59 * analog_scale) / 2) - ((41 * analog_scale) / 2)))
arrowkeys_area_size = 19.675
arrowkeys_back_area_size = 45
joystick_type = 0
settingsx = 5
settingsy = 5
edit = 0
black_fade = 0
text_black_fade = 0
controls_opacity = 0.5
