message[0] = "* To: Head Office	"
message[1] = "* More tests are underway, both#  biological and mechanical.	"
message[2] = "* We don't know which direction#  will ultimately be best for#  monsterkind yet.	"
message[3] = "* However, the chemistry lab did#  have a breakthrough regarding a#  white plant.	"
message[4] = "* I'll get back to you on that#  once further testing has#  commenced.	"
message[5] = "* - Science Division"
color = 1
message_col[0][0] = "* To:            	"
message_col[1][0] = "* More tests are underway, both#  biological and mechanical.	"
message_col[2][0] = "* We don't know which direction#  will ultimately be best for#  monsterkind yet.	"
message_col[3][0] = "* However, the chemistry lab did#  have a breakthrough regarding a#  white plant.	"
message_col[4][0] = "* I'll get back to you on that#  once further testing has#  commenced.	"
message_col[5][0] = "* - Science Division"
col_modif[0] = 8421376
