message[0] = "* To: Science Division	"
message[1] = "* Employees have reported the#  generator is showing more wear#  than ever.	"
message[2] = "* The engineers predict the#  machine won't last longer than#  one year from now.	"
message[3] = "* I need you to speed up the#  testing of alternate power#  sources.	"
message[4] = "* The Underground depends on it."
message[5] = "* - Head Office"
color = 1
message_col[0][0] = "      Science Division"
col_modif[0] = 8421376
