message[0] = "* Help wanted for Project:#  Steam!	"
message[1] = "* Are you a monster with an#  above average IQ?	"
message[2] = "* Probably not. But in case you#  are, we NEED YOUR KNOWLEDGE!	"
message[3] = "* King ASGORE has called on the#  greatest monster minds to help#  develop society!	"
message[4] = "* Scientists, engineers,#  mathematicians, janitors - you#  name it!	"
message[5] = "* Sign up at the King's#  settlement and make your way#  southeast.	"
message[6] = "* You'll know you've arrived#  when you see a metallic#  construction site.	"
message[7] = "* The Steamworks: Tomorrow means#  the Surface!"
