message[0] = "* Today's assignment: Compound#  mixing!"
message[1] = "* The head office said we have#  free use over the Compound#  Computer for today.	"
message[2] = "* They also said the machine#  exploding and killing us all is#  a risk they're willing to take."
message[3] = "* So grab anything you can and#  toss it in! 	"
message[4] = "* Have fun!"
