damage_number = scr_determine_damage_number_enemy("guardener", "void", "void")
launch_sound = audio_play_sound(snd_guardener_arm_launched, 1, false)
launch_dir = "down"
launch_speed = 10
warning_col = 255
warning_draw = 1
warning_count = 2
scene = -1
arm_return = 0
alarm[0] = 5
depth = (obj_heart_battle_fighting_parent.depth + 1)
