message[0] = "Por años, los monstruos#han sido sellados #por un poderoso hechizo."
message[1] = "Un hechizo que sólo podía#romperse con siete#ALMAS humanas."
message[2] = "Su rey era pacífico#y deseaba evitar#más conflictos..."
message[3] = "Pero eventualmente declaró#que cualquier humano que#cayera..."
message[4] = "Moriría..."
message[5] = "Monte Ebott..."
message[6] = "Pocos humanos han desafiado#esta montaña."
message[7] = "Aquellos que lo hicieron...#no se les volvió#a ver."
message_current = 0
message_end = 7
message_draw = ""
increase = 1
characters = 0
hold = 0
message_length = string_length(message[message_current])
counter = 0
counter_max = 2
increase_message_count = 0
