var yy = ((__view_get((1 << 0), 0) / 1.2) - 100)
for (var i = 0; i <= room_width; i += background_get_width(mountain_bg2_layer1))
    draw_background(mountain_bg2_layer1, (__view_get((0 << 0), 0) + i), yy)
for (i = 0; i <= room_width; i += background_get_width(mountain_bg2_layer2))
    draw_background(mountain_bg2_layer2, ((__view_get((0 << 0), 0) + i) / 1.05), (120 + yy))
for (i = 0; i <= room_width; i += background_get_width(mountain_bg2_layer3))
    draw_background(mountain_bg2_layer3, ((__view_get((0 << 0), 0) / 1.07) + i), (118 + yy))
for (i = 0; i <= room_width; i += background_get_width(mountain_bg2_layer4))
    draw_background(mountain_bg2_layer4, ((__view_get((0 << 0), 0) / 1.1) + i), (114 + yy))
for (i = 0; i <= room_width; i += sprite_get_width(spr_mountain_bg_layer7))
    draw_sprite(spr_mountain_bg_layer7, -1, ((__view_get((0 << 0), 0) / 1.1) + i), (68 + yy))
