compound_id = "noone"
robot_item_is_jumping = 0
robot_item_is_carried = 0
robot_item_can_pickup = 1
robot_item_x_target = 0
robot_item_y_target = 0
robot_item_y_offset = 0
message[0] = "* "
solid = 0
depth = -420
