damage_number = scr_determine_damage_number_enemy("ceroba", "void", "void")
state = 0
can_move = 0
attack_distance = 0
attack_dir = 90
bullet_speed = 2
bullet_speed_2 = 0.5
bullet_speed_2_max = (bullet_speed_2 * 3)
attack_target_x = x
attack_target_y = y
creator = obj_quote_battle_ceroba_outro_4
image_speed = 0.2
fade_out = 0
alarm[0] = 150
