message[0] = "* Safety is priority!	"
message[1] = "* - Wear your Steamworks Safety#  Goggles during work hours!	"
message[2] = "* - Always keep your Steamworks#  ID with you!	"
message[3] = "* - Decontaminate yourself of#  any biohazards before leaving#  the premises!	"
message[4] = "* - But most of all, have fun :)"
