anim_loop_time = (room_speed * 6)
anim_stretch_current = 1
anim_stretch_max = 1.1
anim_stage = 1
anim_inc_multiplier = 2
anim_inc_multiplier_max = 2
anim_head_offset = (y - obj_pedla_head.y)
anim_hands_offset = (y - obj_pedla_hands.y)
death_sprite = 0
image_speed = 0
damage_disjoint_count = 0
damage_disjoint_x = 0
no_loop_damage_disjoint_count = 0
starting_point_x = x
starting_point_y = y
no_loop_create_clouds = 0
enemy_hurt_noise = 587
enemy_hurt_pitch = 1.2
