arcade_intro = 1
arcade_intro_alpha = 1
alarm[0] = 45
arcade_boss = 0
arcade_lives = 3
arcade_prnd[0] = 180
arcade_prnd[1] = 220
arcade_prnd[2] = 1000
arcade_score = 0
arcade_upgrade_score = 100
arcade_miniboss_score = 300
arcade_boss_score = 1000
arcade_start_screen = 0
arcade_game_over = 0
arcade_game_win = 0
arcade_game_theme = 0
arcade_game_boss_theme = 0
audio_play_sound(mus_mew_intro, 1, false)
