if live_call()
    return global.live_result;
var xx = 160
var yy = 60
draw_sprite_ext(spr_dialoguebox, 1, xx + 5, (yy + 56), 2.7, 2.6, image_angle, c_white, image_alpha)
draw_sprite_ext(spr_dialoguebox, 0, xx + 5, (yy + 56), 2.6, 2.5, image_angle, c_white, image_alpha)
draw_set_colour(c_white)
draw_set_font(fnt_battle)
for (var n = 0; n < ds_list_size(global.fast_travel_list); n++)
{
    adondeir = ds_list_find_value(global.fast_travel_list, n)
    cuartos = ds_map_create()
    ds_map_add(cuartos, "Wild East - Farm", "Salvaje Este - Granja")
    ds_map_add(cuartos, "Snowdin - Forest", "Snowdin - Bosque")
    ds_map_add(cuartos, "Dunes - West Mines", "Dunas - Minas Oeste")
    ds_map_add(cuartos, "Dunes - Oasis Valley", "Dunas - Valle Oasis")
    ds_map_add(cuartos, "Hotland - Crossroads", "Hotland - Intersección")
    ds_map_add(cuartos, "The Furnace", "El Horno")
    ds_map_add(cuartos, "Dark Ruins - Entrance", "Ruinas Oscuras - Entrada")
    ds_map_add(cuartos, "Dark Ruins - Main", "Ruinas Oscuras - Atrio")
    ds_map_add(cuartos, "Dark Ruins - Cliff", "Ruinas Oscuras - Abismo")
    ds_map_add(cuartos, "Dark Ruins - Puzzle", "Ruinas Oscuras - Puzzle")
    ds_map_add(cuartos, "Dark Ruins - Hall", "Ruinas Oscuras - Salón")
    ds_map_add(cuartos, "Snowdin - Delta Rock", "Snowdin - Roca Delta")
    ds_map_add(cuartos, "Snowdin - Ruined Shack", "Snowdin - Cabaña Rota")
    ds_map_add(cuartos, "Snowdin - Pathway", "Snowdin - Sendero")
    ds_map_add(cuartos, "Snowdin - Resort", "Snowdin - Resort")
    ds_map_add(cuartos, "Snowdin - Corridor", "Snowdin - Corredor")
    ds_map_add(cuartos, "Dunes - Cave", "Dunas - Cueva")
    ds_map_add(cuartos, "Dunes - Tree", "Dunas - Árbol")
    ds_map_add(cuartos, "Mines - Elevator", "Minas - Elevador")
    ds_map_add(cuartos, "Mines - Minecart", "Minas - Vagoneta")
    ds_map_add(cuartos, "Dunes - Mountaintop", "Dunas - Cima de montaña")
    ds_map_add(cuartos, "Dunes - Playground", "Dunas - Parque infantil")
    ds_map_add(cuartos, "Dunes - Well", "Dunas - Pozo")
    ds_map_add(cuartos, "Wild East - Town", "Salvaje Este - Pueblo")
    ds_map_add(cuartos, "Wild East - Outskirts", "Salvaje Este - Afueras")
    ds_map_add(cuartos, "Wild East - Sunnyside", "Salvaje Este - Lado Sol")
    ds_map_add(cuartos, "Steamw. - Generator", "Steamw. - Generador")
    ds_map_add(cuartos, "Steamw. - Raised Path", "Steamw. - Camino Elevado")
    ds_map_add(cuartos, "Steamw. - Lake", "Steamw. - Lago")
    ds_map_add(cuartos, "Steamw. - Offices", "Steamw. - Oficinas")
    ds_map_add(cuartos, "Steamw. - ???", "Steamw. - ???")
    ds_map_add(cuartos, "Steamw. - Commons", "Steamw. - Cafetería")
    ds_map_add(cuartos, "Greenhouse", "Invernadero")
    ds_map_add(cuartos, "Steamw. - Crossroads", "Steamw. - Cruces")
    ds_map_add(cuartos, "Steamw. - Laboratory", "Steamw. - Laboratorio")
    ds_map_add(cuartos, "Steamw. - Botany Hall", "Steamw. - Botánico")
    ds_map_add(cuartos, "Factory - Lobby", "Fábrica - Vestíbulo")
    ds_map_add(cuartos, "Factory - Offices", "Fábrica - Oficinas")
    ds_map_add(cuartos, "The Furnace", "El Horno")
    ds_map_add(cuartos, "A Road Ahead", "Camino por Delante")
    ds_map_add(cuartos, "Estate", "Propiedad")
    ds_map_add(cuartos, "Apt. Complex", "Complejo de Apartamentos")
    ds_map_add(cuartos, "New Home", "Nuevo Hogar")
    ds_map_add(cuartos, "Steamw. - C. Station", "Steamw. - C. Estación")
    if ds_map_exists(cuartos, adondeir)
        adondeir = ds_map_find_value(cuartos, adondeir)
    draw_set_color(c_white)
    draw_text((xx - 60), ((yy - 30) + ((n + 1) * 15)), string_hash_to_newline(adondeir))
}
draw_sprite(encounter_heart, 0, (xx - 70), ((yy - 22) + (15 * item_selected)))
