name: Copiar código modificado

on:
    push:
        branches:
            - main
        # paths:
        #   - 'Export_Code/**.gml'

jobs:
    copy_code:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout código"
              uses: actions/checkout@v2

            - id: files 
              uses: jitterbit/get-changed-files@v1
            
            - name: "Copiar archivos modificados"
              run: |
                    mkdir Copy_Code

                    ls

                    for changed_file in ${{ steps.files.outputs.all }}; do
                        echo "Changed file: $changed_file"
                        cp $changed_file Copy_Code 
                    done

                    ls Copy_Code
                                                                                                                                                            
