name: Copiar código modificado

on:
    push:
        branches:
            - main
        # paths:
        #   - 'Export_Code/**.gml'

jobs:
    copy_code:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout código"
              uses: actions/checkout@v2

            - name: Copiar archivos modificados
              run: |
                    mkdir Copy_Code
                    find Export_Code -type f -newermt "$(git log -1 --format=%cd --date=format:'%Y-%m-%d %H:%M:%S' Export_Code)" -exec cp {} Copy_Code/ \;
        
                                                                                                                                                            
